TRUNK-6187 ClassCastException: com.sun.proxy.$Proxy183 cannot be cast to org.openmrs.api.impl.UserServiceImpl
The OpenMRS database setup wizard fails with this error:

WARN - InitializationFilter$InitializationCompletion$1.run(1820) |2023-09-28T13:18:26,152| Unable to complete the startup.
java.lang.ClassCastException: com.sun.proxy.$Proxy183 cannot be cast to org.openmrs.api.impl.UserServiceImpl
	at org.openmrs.web.filter.initialization.InitializationFilter$InitializationCompletion$1.run(InitializationFilter.java:1798) [openmrs-web-2.7.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]

(cherry picked from commit 452a088de763aae754d4f2be1074f1707c6c3e48)
(cherry picked from commit 35f1524c07dcca83e04a6f5e3d9c0dc8af2c4faa)