Fixing java.lang.NoClassDefFoundError: javax/servlet/jsp/jstl/core/Config on tomcat (cherry picked from commit 09483b0b1a50ed926b9098d9df60579e52ea1015)