TRUNK-257: Add Feature to enable moving Encounter Data to a different patient
TRUNK-3980: Add back button support for patient search page

TRUNK-257 Add Feature to enable moving Encounter Data to a different patient

TRUNK-257 Add Feature to enable moving Encounter Data to a different patient

TRUNK-257 Add Feature to enable moving Encounter Data to a different patient

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient - service API methods

TRUNK-257 Add Feature to enable moving Encounter Data to a different patient

TRUNK-257 Add Feature to enable moving Encounter Data to a different patient

TRUNK-257 Add Feature to enable moving Encounter Data to a different patient

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient - service API methods

TRUNK-3943: Support data preserve on browser back button in concept search page

Manage preferred status for PersonName, PersonAddress and
PatientIdentifier in the API - TRUNK-2200

Follow up to set the preferred or fully specified name for a concept
list item - TRUK-3232

Manage preferred status for PersonName, PersonAddress and
PatientIdentifier in the API - TRUNK-2200

Taken care of patient identifier and also updated savePatient - TRUNK-2200

get folder for module web files programatically - TRUNK-1589

Made some changes - TRUNK-1589

Made more changes to the tests - TRUNK-1589

Applied auto format changes - TRUNK-1589

NonUniqueObjectException: a different object with the same identifier
value was already associated with the session: [org.openmrs.Patient#] -
TRUNK-3728

Applying auto format changes - TRUNK-3728

TRUNK-3979: LoggingAdvice should also log which user is performing an action when an error occurs

Null check and taking systemId if username is empty

User null check

Fix of code duplication

Search for patient by identifier fails when identifier is made of only
letters - TRUNK-3822

Follow up - TRUNK-3822

Follow up to fix some issues - TRUNK-3822

Fixed patientService.getPatientCount method - TRUNK-3822

Follow up to fix failing unit test - TRUNK-3822

Apply auto format changes and fixed HibernateEncounterDAO - TRUNK-3822

OpenMRS crashes irrecoverably if particular errors occur during module loading  - TRUNK-2850

TRUNK-3992: PersonByNameComparator should be case-insensitive

TRUNK-3206: Added test methods for HibernatePatientDAO.HibernatePatientDAO.getPatientIdentifierTypes

Removing unused message for: Force password change page help text should
reflect security global properties - TRUNK-1868

Changing the number of characters from 49 to 50 as expected in
PersonNameValidatorTest for: Add regex validation to PersonNameValidator
- TRUNK-2616

TRUNK-257 Add Feature to enable moving Encounter Data to a different patient

TRUNK-257 Add Feature to enable moving Encounter Data to a different patient

TRUNK-257 Add Feature to enable moving Encounter Data to a different patient

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient - service API methods

TRUNK-257 Add Feature to enable moving Encounter Data to a different patient

TRUNK-257 Add Feature to enable moving Encounter Data to a different patient

TRUNK-257 Add Feature to enable moving Encounter Data to a different patient

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient - service API methods

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient - service API methods

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient - user interface

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient - user interface

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient - user interface

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient - user interface

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient - user interface

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient

TRUNK-257: Add Feature to enable moving Encounter Data to a different patient - user interface

TRUNK-257 - rebase with upstrem master

TRUNK-257 - rebase with upstrem master

TRUNK-257 - rebase with upstrem master - remove *.orig files

TRUNK-257 - merge with upstream/master

TRUNK-257 - fix junit tests

remove not my changes

remove unecessary changes

TRUNK-257 - review changes v.1

TRUNK-257 - review changes v.2

TRUNK-257 - review changes v.3